spring.application.name=space-booking
# Konsola H2 - podglad bazy w przegladarce
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:spacebookingdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate - automatycznie stworzy tabele na podstawie kodu
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# formatuje SQL (czytelniej):
spring.jpa.properties.hibernate.format_sql=true 
#wartosci jako ?  :
spring.jpa.show-sql=true 
#mozna uzyc ponizszego na bindowanie parametrow (uwaga na dane wrazliwe)
#logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.hibernate.ddl-auto=update
#dba by najpierw powsta?y tabele (Hibernate), a potem wykona? si? data.sql
spring.jpa.defer-datasource-initialization=true
#inicjalizuje baze danymi na start
spring.sql.init.mode=always


!none: (albo brak ustawienia): Hibernate nie rusza schematu.
!Zaklada, ze baza/migracje sa ogarniete osobno.
!validate: Hibernate sprawdza, czy schemat pasuje do encji.
!Jezli nie pasuje to aplikacja nie wstanie. Nic nie zmienia w bazie.
!update:Próbuje dostosowac schemat bez utraty danych.
!Dobre na dev, ale bywa nieprzewidywalne przy wiekszych zmianach.
!create: Przy starcie tworzy schemat od zera (zwykle dropuje i tworzy ponownie). Dane znikaja.
!create-drop: Jak create, ale dodatkowo przy zamknieciu aplikacji robi drop. Typowo do testów.
